[clone]
root = "/tmp/grit-test/clone"

[clone.sources]
# my-company = "git@github.example.com:{{slug}}.git"
github = "file:///tmp/grit-repos/{{slug}}.git"

[index]
paths = ["/tmp/grit-test/clone"]
store = "/tmp/grit-test/cache"
