name: CI

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.41
      - name: unit-test
        run: make test
      - name: ci
        run: make ci

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - unit-test
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}